ALTER TABLE `donations`
  MODIFY `status` enum('received','pending','assessed','published','rejected','archived') DEFAULT 'pending',
  ADD COLUMN IF NOT EXISTS `evaluation_status` enum('pending','approved_volunteer','approved_self_delivery','rejected') DEFAULT 'pending' AFTER `status`,
  ADD COLUMN IF NOT EXISTS `delivery_method` enum('self_delivery','volunteer_assist','donor') DEFAULT 'volunteer_assist' AFTER `evaluation_status`,
  ADD COLUMN IF NOT EXISTS `approval_notes` text DEFAULT NULL AFTER `delivery_method`,
  ADD COLUMN IF NOT EXISTS `approved_at` datetime DEFAULT NULL AFTER `approval_notes`,
  ADD COLUMN IF NOT EXISTS `approved_by` int(11) DEFAULT NULL AFTER `approved_at`,
  ADD COLUMN IF NOT EXISTS `rejection_reason` text DEFAULT NULL AFTER `approved_by`,
  ADD COLUMN IF NOT EXISTS `rejected_at` datetime DEFAULT NULL AFTER `rejection_reason`,
  ADD COLUMN IF NOT EXISTS `published_at` datetime DEFAULT NULL AFTER `rejected_at`,
  ADD COLUMN IF NOT EXISTS `current_status` enum('waiting_pickup','volunteer_received','in_transit','at_foodbank','inspection_complete') DEFAULT 'waiting_pickup' AFTER `published_at`,
  ADD COLUMN IF NOT EXISTS `status_updated_at` datetime DEFAULT NULL AFTER `current_status`,
  ADD COLUMN IF NOT EXISTS `split_count` int(11) DEFAULT 1 AFTER `status_updated_at`,
  ADD COLUMN IF NOT EXISTS `item_name` varchar(100) DEFAULT NULL AFTER `updated_at`,
  ADD COLUMN IF NOT EXISTS `weight_kg` decimal(10,2) DEFAULT NULL AFTER `item_name`,
  ADD COLUMN IF NOT EXISTS `size_description` varchar(100) DEFAULT NULL AFTER `weight_kg`,
  ADD COLUMN IF NOT EXISTS `expiry_date` date DEFAULT NULL AFTER `size_description`,
  ADD COLUMN IF NOT EXISTS `pickup_deadline` datetime DEFAULT NULL AFTER `expiry_date`,
  ADD COLUMN IF NOT EXISTS `delivery_option` enum('donor_delivery','volunteer_delivery','food_bank_pickup') DEFAULT 'volunteer_delivery' AFTER `pickup_deadline`,
  ADD COLUMN IF NOT EXISTS `vehicle_type` enum('car','motorcycle','none') DEFAULT 'none' AFTER `delivery_option`,
  ADD COLUMN IF NOT EXISTS `photo_path` varchar(255) DEFAULT NULL AFTER `vehicle_type`,
  ADD COLUMN IF NOT EXISTS `evaluation_notes` text DEFAULT NULL AFTER `photo_path`,
  ADD COLUMN IF NOT EXISTS `seal_code` varchar(30) DEFAULT NULL AFTER `evaluation_notes`,
  ADD COLUMN IF NOT EXISTS `need_inspection` tinyint(1) DEFAULT 1 AFTER `seal_code`,
  ADD COLUMN IF NOT EXISTS `inspection_notes` text DEFAULT NULL AFTER `need_inspection`,
  ADD COLUMN IF NOT EXISTS `donor_address` varchar(255) DEFAULT NULL AFTER `inspection_notes`,
  ADD COLUMN IF NOT EXISTS `reward_options` text DEFAULT NULL AFTER `donor_address`,
  ADD COLUMN IF NOT EXISTS `delivery_date` date DEFAULT NULL AFTER `reward_options`,
  ADD COLUMN IF NOT EXISTS `delivery_time` time DEFAULT NULL AFTER `delivery_date`,
  ADD COLUMN IF NOT EXISTS `delivery_address` varchar(255) DEFAULT NULL AFTER `delivery_time`,
  ADD COLUMN IF NOT EXISTS `beneficiary_id` int(11) DEFAULT NULL AFTER `delivery_address`,
  ADD COLUMN IF NOT EXISTS `dispatch_contact_name` varchar(100) DEFAULT NULL AFTER `beneficiary_id`,
  ADD COLUMN IF NOT EXISTS `dispatch_contact_phone` varchar(30) DEFAULT NULL AFTER `dispatch_contact_name`,
  ADD COLUMN IF NOT EXISTS `dispatch_vehicle_info` varchar(150) DEFAULT NULL AFTER `dispatch_contact_phone`;

CREATE TABLE IF NOT EXISTS `donation_items` (
  `item_id` int(11) NOT NULL AUTO_INCREMENT,
  `donation_id` int(11) NOT NULL,
  `item_name` varchar(100) NOT NULL,
  `brand` varchar(100) DEFAULT NULL,
  `specification` varchar(150) DEFAULT NULL,
  `quantity` decimal(10,2) NOT NULL,
  `unit` varchar(20) NOT NULL DEFAULT '件',
  `expiry_date` date DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`item_id`),
  KEY `idx_donation_items_donation_id` (`donation_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;